package br.com.nutribemrefeicoescoletivas.view;

import br.com.nutribemrefeicoescoletivas.bean.PermissaoBean;
import br.com.nutribemrefeicoescoletivas.bean.UsuarioBean;
import br.com.nutribemrefeicoescoletivas.control.UsuarioController;
import br.com.nutribemrefeicoescoletivas.mail.ConfigMail;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.mail.EmailException;

public class CadastroUsuario extends javax.swing.JDialog {

    /**
     * Creates new form CadastroUsuario
     * @param parent
     * @param modal
     */
    public CadastroUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }
    
    private void LimpaCampos(){
        NaADM.setSelected(false);
        NaRH.setSelected(false);
        NaUP.setSelected(false);
        SoAdmissao.setSelected(false);
        SoDemissao.setSelected(false);
        SoFerias.setSelected(false);
        SoPromocao.setSelected(false);
        ApAdmissao.setSelected(false);
        ApDemissao.setSelected(false);
        ApFerias.setSelected(false);
        ApPromocao.setSelected(false);
        AcAdmissao.setSelected(false);
        AcDemissao.setSelected(false);
        AcFerias.setSelected(false);
        AcPromocao.setSelected(false);
        CpEmail.setText("");
        CpLogin.setText("");
        CpNome.setText("");
    }
    
    public String gerarString() {
        String letras = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvXxYyWwZz123456789";
        Random random = new Random();
        StringBuilder saida = new StringBuilder();
        for (int i = 0; i < 8; i++) { 
            saida.append(letras.charAt(random.nextInt(letras.length()))); 
        } 
        return saida.toString(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CpNome = new javax.swing.JTextField();
        CpLogin = new javax.swing.JTextField();
        CpEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SoFerias = new javax.swing.JCheckBox();
        ApFerias = new javax.swing.JCheckBox();
        AcFerias = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        SoDemissao = new javax.swing.JCheckBox();
        ApDemissao = new javax.swing.JCheckBox();
        AcDemissao = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        AcPromocao = new javax.swing.JCheckBox();
        ApPromocao = new javax.swing.JCheckBox();
        SoPromocao = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        AcAdmissao = new javax.swing.JCheckBox();
        ApAdmissao = new javax.swing.JCheckBox();
        SoAdmissao = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        BTSalvar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        NaADM = new javax.swing.JRadioButton();
        NaRH = new javax.swing.JRadioButton();
        NaUP = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Fomulário Cadastro de Usuários");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Login:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("E-mail:");

        CpNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CpLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CpEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Lista de Permissões");

        SoFerias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SoFerias.setText("Solicitar");
        SoFerias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoFeriasMouseClicked(evt);
            }
        });

        ApFerias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ApFerias.setText("Aprovar");
        ApFerias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApFeriasMouseClicked(evt);
            }
        });

        AcFerias.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcFerias.setText("Acompanhar");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Férias");

        SoDemissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SoDemissao.setText("Solicitar");
        SoDemissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoDemissaoMouseClicked(evt);
            }
        });

        ApDemissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ApDemissao.setText("Aprovar");
        ApDemissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApDemissaoMouseClicked(evt);
            }
        });

        AcDemissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcDemissao.setText("Acompanhar");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Demissão");

        AcPromocao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcPromocao.setText("Acompanhar");

        ApPromocao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ApPromocao.setText("Aprovar");
        ApPromocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApPromocaoMouseClicked(evt);
            }
        });

        SoPromocao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SoPromocao.setText("Solicitar");
        SoPromocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoPromocaoMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Promoção");

        AcAdmissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcAdmissao.setText("Acompanhar");

        ApAdmissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ApAdmissao.setText("Aprovar");
        ApAdmissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApAdmissaoMouseClicked(evt);
            }
        });

        SoAdmissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SoAdmissao.setText("Solicitar");
        SoAdmissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SoAdmissaoMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Admissão");

        BTSalvar.setText("Salvar");
        BTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalvarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Nível de Acesso");

        NaADM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NaADM.setText("Administrador");
        NaADM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NaADMMouseClicked(evt);
            }
        });

        NaRH.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NaRH.setText("RH");
        NaRH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NaRHMouseClicked(evt);
            }
        });

        NaUP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NaUP.setText("Usuário Padrão");
        NaUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NaUPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CpNome, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(CpLogin)
                            .addComponent(CpEmail)))
                    .addComponent(jLabel7)
                    .addComponent(BTSalvar)
                    .addComponent(ApFerias)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NaADM)
                        .addGap(18, 18, 18)
                        .addComponent(NaRH)
                        .addGap(18, 18, 18)
                        .addComponent(NaUP))
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AcFerias)
                            .addComponent(SoFerias))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApDemissao)
                            .addComponent(jLabel9)
                            .addComponent(SoDemissao)
                            .addComponent(AcDemissao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApPromocao)
                            .addComponent(jLabel11)
                            .addComponent(SoPromocao)
                            .addComponent(AcPromocao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SoAdmissao)
                            .addComponent(ApAdmissao)
                            .addComponent(jLabel12)
                            .addComponent(AcAdmissao))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(ApFerias))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(ApDemissao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(7, 7, 7)
                        .addComponent(ApPromocao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(ApAdmissao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SoFerias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AcFerias))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SoDemissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AcDemissao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SoPromocao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AcPromocao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SoAdmissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AcAdmissao)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NaADM)
                    .addComponent(NaRH)
                    .addComponent(NaUP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BTSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalvarActionPerformed
        UsuarioBean ub = new UsuarioBean();
        PermissaoBean pb = new PermissaoBean();
        try {
            ub.setLogin(CpLogin.getText());
            ub.setEmail(CpEmail.getText());
            ub.setNome(CpNome.getText());
            ub.setSenha(gerarString());
            
            /*GET DAS PERMISSÕES*/
            if(ApFerias.isSelected()){
                pb.setFerias("APR");
            }else{
                if(!ApFerias.isSelected() && SoFerias.isSelected()){
                    pb.setFerias("SOL");
                }else{
                    if(!SoFerias.isSelected() && AcFerias.isSelected()){
                        pb.setFerias("ACO");
                    }
                }
            }
            if(ApDemissao.isSelected()){
                pb.setDemissao("APR");
            }else{
                if(!ApDemissao.isSelected() && SoDemissao.isSelected()){
                    pb.setDemissao("SOL");
                }else{
                    if(!SoDemissao.isSelected() && AcDemissao.isSelected()){
                        pb.setDemissao("ACO");
                    }
                }
            }
            if(ApPromocao.isSelected()){
                pb.setPromocao("APR");
            }else{
                if(!ApPromocao.isSelected() && SoPromocao.isSelected()){
                    pb.setPromocao("SOL");
                }else{
                    if(!SoPromocao.isSelected() && AcPromocao.isSelected()){
                        pb.setPromocao("ACO");
                    }
                }
            }
            if(ApAdmissao.isSelected()){
                pb.setAdmissao("APR");
            }else{
                if(!ApAdmissao.isSelected() && SoAdmissao.isSelected()){
                    pb.setAdmissao("SOL");
                }else{
                    if(!SoAdmissao.isSelected() && AcAdmissao.isSelected()){
                        pb.setAdmissao("ACO");
                    }
                }
            }
            
            if(NaADM.isSelected()){
                pb.setNvAcesso("ADM");
            }else{
                if(NaRH.isSelected()){
                    pb.setNvAcesso("RH");
                }else{
                    if(NaUP.isSelected()){
                        pb.setNvAcesso("UP");
                    }else{
                        pb.setNvAcesso("UP");
                    }
                }
            }
            System.out.println(pb.getNvAcesso());
            /*FIM*/
            try {
                if(new UsuarioController().cadastrar( ub, pb )){
                    if(new ConfigMail().enviaEmailFormatoHtml( ub )){
                        JOptionPane.showMessageDialog(this, "Usuário Cadastrado e e-mail enviado.");
                        LimpaCampos();
                    }else{
                        JOptionPane.showMessageDialog(this, "Usuário Cadastrado e e-mail não enviado.");
                        LimpaCampos();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Falha ao cadastrar Usuário.");
                }
            } catch (SQLException | NoSuchAlgorithmException | UnsupportedEncodingException ex) {
                Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (EmailException | MalformedURLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTSalvarActionPerformed

    private void SoFeriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoFeriasMouseClicked
        if(SoFerias.isSelected()){
            AcFerias.setSelected(true);
            AcFerias.setEnabled(false);
        }else{
            AcFerias.setSelected(false);
            AcFerias.setEnabled(true);
        }
    }//GEN-LAST:event_SoFeriasMouseClicked

    private void ApFeriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApFeriasMouseClicked
        if(ApFerias.isSelected()){
            AcFerias.setSelected(true);
            AcFerias.setEnabled(false);
            SoFerias.setSelected(true);
            SoFerias.setEnabled(false);
        }else{
            AcFerias.setSelected(false);
            AcFerias.setEnabled(true);
            SoFerias.setSelected(false);
            SoFerias.setEnabled(true);
        }
    }//GEN-LAST:event_ApFeriasMouseClicked

    private void SoDemissaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoDemissaoMouseClicked
        if(SoDemissao.isSelected()){
            AcDemissao.setSelected(true);
            AcDemissao.setEnabled(false);
        }else{
            AcDemissao.setSelected(false);
            AcDemissao.setEnabled(true);
        }
    }//GEN-LAST:event_SoDemissaoMouseClicked

    private void SoPromocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoPromocaoMouseClicked
        if(SoPromocao.isSelected()){
            AcPromocao.setSelected(true);
            AcPromocao.setEnabled(false);
        }else{
            AcPromocao.setSelected(false);
            AcPromocao.setEnabled(true);
        }
    }//GEN-LAST:event_SoPromocaoMouseClicked

    private void ApPromocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApPromocaoMouseClicked
        if(ApPromocao.isSelected()){
            AcPromocao.setSelected(true);
            AcPromocao.setEnabled(false);
            SoPromocao.setSelected(true);
            SoPromocao.setEnabled(false);
        }else{
            AcPromocao.setSelected(false);
            AcPromocao.setEnabled(true);
            SoPromocao.setSelected(false);
            SoPromocao.setEnabled(true);
        }
    }//GEN-LAST:event_ApPromocaoMouseClicked

    private void SoAdmissaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SoAdmissaoMouseClicked
        if(SoAdmissao.isSelected()){
            AcAdmissao.setSelected(true);
            AcAdmissao.setEnabled(false);
        }else{
            AcAdmissao.setSelected(false);
            AcAdmissao.setEnabled(true);
        }
    }//GEN-LAST:event_SoAdmissaoMouseClicked

    private void ApAdmissaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApAdmissaoMouseClicked
        if(ApAdmissao.isSelected()){
            AcAdmissao.setSelected(true);
            AcAdmissao.setEnabled(false);
            SoAdmissao.setSelected(true);
            SoAdmissao.setEnabled(false);
        }else{
            AcAdmissao.setSelected(false);
            AcAdmissao.setEnabled(true);
            SoAdmissao.setSelected(false);
            SoAdmissao.setEnabled(true);
        }
    }//GEN-LAST:event_ApAdmissaoMouseClicked

    private void ApDemissaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApDemissaoMouseClicked
        if(ApDemissao.isSelected()){
            AcDemissao.setSelected(true);
            AcDemissao.setEnabled(false);
            SoDemissao.setSelected(true);
            SoDemissao.setEnabled(false);
        }else{
            AcDemissao.setSelected(false);
            AcDemissao.setEnabled(true);
            SoDemissao.setSelected(false);
            SoDemissao.setEnabled(true);
        }
    }//GEN-LAST:event_ApDemissaoMouseClicked

    private void NaRHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NaRHMouseClicked
        if(NaRH.isSelected()){
            NaADM.setSelected(false);
            NaUP.setSelected(false);
        }
    }//GEN-LAST:event_NaRHMouseClicked

    private void NaADMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NaADMMouseClicked
        if(NaADM.isSelected()){
            NaRH.setSelected(false);
            NaUP.setSelected(false);
        }
    }//GEN-LAST:event_NaADMMouseClicked

    private void NaUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NaUPMouseClicked
        if(NaUP.isSelected()){
            NaADM.setSelected(false);
            NaRH.setSelected(false);
        }
    }//GEN-LAST:event_NaUPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CadastroUsuario dialog = new CadastroUsuario(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AcAdmissao;
    private javax.swing.JCheckBox AcDemissao;
    private javax.swing.JCheckBox AcFerias;
    private javax.swing.JCheckBox AcPromocao;
    private javax.swing.JCheckBox ApAdmissao;
    private javax.swing.JCheckBox ApDemissao;
    private javax.swing.JCheckBox ApFerias;
    private javax.swing.JCheckBox ApPromocao;
    private javax.swing.JButton BTSalvar;
    private javax.swing.JTextField CpEmail;
    private javax.swing.JTextField CpLogin;
    private javax.swing.JTextField CpNome;
    private javax.swing.JRadioButton NaADM;
    private javax.swing.JRadioButton NaRH;
    private javax.swing.JRadioButton NaUP;
    private javax.swing.JCheckBox SoAdmissao;
    private javax.swing.JCheckBox SoDemissao;
    private javax.swing.JCheckBox SoFerias;
    private javax.swing.JCheckBox SoPromocao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
