/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.nutribemrefeicoescoletivas.view;

import br.com.nutribemrefeicoescoletivas.bean.FuncionarioBean;
import br.com.nutribemrefeicoescoletivas.control.FuncionarioController;
import br.com.nutribemrefeicoescoletivas.model.TelaCadastroFuncionarioModel;
import br.com.nutribemrefeicoescoletivas.tools.jTableGrid;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.collections4.IteratorUtils;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
/**
 *
 * @author Cleiton
 */
public class FuncionarioCadastro extends javax.swing.JDialog {

    /**
     * Creates new form FuncionarioCadastro
     * @param parent
     * @param modal
     */
    private ArrayList<FuncionarioBean> ErroLista = new ArrayList<>();
    private int cont = 0, total;
    public FuncionarioCadastro(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        ConfgTable();
    }
    
    private void ConfgTable() throws SQLException {
        TableFuncionario.setModel (new TelaCadastroFuncionarioModel(new FuncionarioController().buscar()));
        new jTableGrid().FormatarJtable(TableFuncionario, new int[]{304,100,154,120});

    } 
    
     private List<?> toList(Iterator<?> iterator){
         return IteratorUtils.toList(iterator);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTArquivo = new javax.swing.JButton();
        CaminhoArquivo = new javax.swing.JTextField();
        NomeArquivo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFuncionario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        FuncionarioCadastro = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTArquivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BTArquivo.setText("Localizar Arquivo de Funcionário");
        BTArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTArquivoActionPerformed(evt);
            }
        });

        CaminhoArquivo.setEditable(false);
        CaminhoArquivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        NomeArquivo.setEditable(false);
        NomeArquivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TableFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableFuncionario);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Cadastrar/Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FuncionarioCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Mostrar Erros de Cadastro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Fomulário de Cadastro/Atualização");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Lista de Colaboradores Cadastrados Ativos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(BTArquivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CaminhoArquivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FuncionarioCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FuncionarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTArquivoActionPerformed
        FuncionarioCadastro.setText("");
        cont = 0;
        total = 0;
        
        FileNameExtensionFilter ff = new FileNameExtensionFilter("Arquivo do Excel (.xls)", "xls" );
        JFileChooser jf = new JFileChooser();
        jf.addChoosableFileFilter(ff);
        jf.setAcceptAllFileFilterUsed(false);
        
        int rJf = jf.showOpenDialog(this);
        if(rJf == jf.APPROVE_OPTION){
            File aq = jf.getSelectedFile();
            try{
                CaminhoArquivo.setText( aq.getAbsolutePath() );
                NomeArquivo.setText( aq.getName() );
            }catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_BTArquivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            FileInputStream is = new FileInputStream(CaminhoArquivo.getText());
            //System.out.println(CaminhoArquivo.getText());

            Workbook planilha = new HSSFWorkbook(is);
            Sheet pl = planilha.getSheetAt(0);
            List<Row> linha = (List<Row>) toList(pl.iterator());
            
            //linha.remove(0);
            total = pl.getLastRowNum()+1;

            linha.forEach(row ->{
                List<Cell> celula = (List<Cell>) toList(row.cellIterator());
                FuncionarioBean fb = new FuncionarioBean();
                if(!celula.get(0).getStringCellValue().isEmpty()){
                    fb.setNome(celula.get(0).getStringCellValue());
                    fb.setCPF(Long.parseLong(celula.get(4).getStringCellValue()));
                    fb.setCargo(celula.get(1).getStringCellValue());
                    Date data = new java.sql.Date(celula.get(2).getDateCellValue().getTime());
                    fb.setDContrato( data );
                    fb.setSalario(celula.get(5).getNumericCellValue());
                    fb.setIDUnidade((int) celula.get(6).getNumericCellValue());
                    fb.setSituacao((int)celula.get(3).getNumericCellValue());
                    try {
                        if(new FuncionarioController().cadastro(fb)){
                            cont += 1;
                            FuncionarioCadastro.setText(cont+" Funcionário (s) cadastrados/atulizados de "+total);
                            //System.out.println(cont);
                        }else{
                            ErroLista.add(fb);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(FuncionarioCadastro.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    
                }
            });
            ConfgTable();

        } catch (IOException | SQLException ex) {
            Logger.getLogger(FuncionarioCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try{            
            ErroCadastro ec = new ErroCadastro(new JFrame(), true);
            ec.Recebe(ErroLista, this);
            ec.setVisible(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                FuncionarioCadastro dialog = new FuncionarioCadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionarioCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTArquivo;
    private javax.swing.JTextField CaminhoArquivo;
    private javax.swing.JLabel FuncionarioCadastro;
    private javax.swing.JTextField NomeArquivo;
    private javax.swing.JTable TableFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
