package br.com.nutribemrefeicoescoletivas.view;

import br.com.nutribemrefeicoescoletivas.bean.UsuarioBean;
import br.com.nutribemrefeicoescoletivas.control.UsuarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class RHPrincipal extends javax.swing.JFrame {

    private UsuarioBean user = null;
    
    public RHPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
    }

    
    public void RecebeDados(Object ob) throws SQLException{
        UsuarioBean obj = (UsuarioBean) ob;
        user = (UsuarioBean) new UsuarioController().busca(obj);
        Saudacao.setText("Bem vindo "+user.getNome()+"!");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Saudacao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BTUsuarios1 = new javax.swing.JMenu();
        FuncCadastro = new javax.swing.JMenuItem();
        BTArquivos = new javax.swing.JMenu();
        FileUp = new javax.swing.JMenuItem();
        FileDown = new javax.swing.JMenuItem();
        BTUsuarios = new javax.swing.JMenu();
        CadastroUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RH-Online");

        BTUsuarios1.setText("Funcionários");

        FuncCadastro.setText("Cadastrar");
        FuncCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncCadastroActionPerformed(evt);
            }
        });
        BTUsuarios1.add(FuncCadastro);
        FuncCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));

        jMenuBar1.add(BTUsuarios1);

        BTArquivos.setText("Arquivos");

        FileUp.setText("Upload");
        FileUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileUpActionPerformed(evt);
            }
        });
        BTArquivos.add(FileUp);
        FileUp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));

        FileDown.setText("Download");
        FileDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileDownActionPerformed(evt);
            }
        });
        BTArquivos.add(FileDown);
        FileDown.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));

        jMenuBar1.add(BTArquivos);

        BTUsuarios.setText("Usuários");

        CadastroUser.setText("Cadastrar");
        CadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroUserActionPerformed(evt);
            }
        });
        BTUsuarios.add(CadastroUser);
        FileUp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));

        jMenuBar1.add(BTUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Saudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(Saudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileUpActionPerformed
       FileUpload fu = new FileUpload(this, true);
       fu.getInfor(user.getID(), this);
       fu.setVisible(true);
    }//GEN-LAST:event_FileUpActionPerformed

    private void FileDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileDownActionPerformed
       new FileDownload(this, true).setVisible(true);
    }//GEN-LAST:event_FileDownActionPerformed

    private void CadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroUserActionPerformed
        try {
            new CadastroUsuario(this, true).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(RHPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastroUserActionPerformed

    private void FuncCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncCadastroActionPerformed
        try {
            new FuncionarioCadastro(this, true).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RHPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FuncCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RHPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RHPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RHPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RHPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RHPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BTArquivos;
    private javax.swing.JMenu BTUsuarios;
    private javax.swing.JMenu BTUsuarios1;
    private javax.swing.JMenuItem CadastroUser;
    private javax.swing.JMenuItem FileDown;
    private javax.swing.JMenuItem FileUp;
    private javax.swing.JMenuItem FuncCadastro;
    private javax.swing.JLabel Saudacao;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
